- name: Install dependencies for gvm
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - mercurial
    - make
    - binutils
    - bison
    - gcc

- name: Install Golang gvm
  sudo: yes
  sudo_user: "{{ gvm_user }}"
  shell: bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
      executable="/bin/bash"
  ignore_errors: true

- name: Put zshrc for gvm
  sudo: yes
  sudo_user: "{{ gvm_user }}"
  lineinfile: >
    dest="~/.zshrc"
    line='[[ -s "/home/{{ gvm_user }}/.gvm/scripts/gvm" ]] && source "/home/{{ gvm_user }}/.gvm/scripts/gvm"'

- name: Install Golang
  shell: "sudo -iu {{ gvm_user }} export GVM_ROOT=/home/{{ gvm_user }}/.gvm && source /home/{{ gvm_user }}/.gvm/scripts/gvm && gvm install go1.4"
  ignore_errors: true

- name: Use go1.4
  shell: "sudo -iu {{ gvm_user }} export GVM_ROOT=/home/{{ gvm_user }}/.gvm && source /home/{{ gvm_user }}/.gvm/scripts/gvm && gvm use go1.4"

- name: Install Golang target version
  shell: "sudo -iu {{ gvm_user }} export GVM_ROOT=/home/{{ gvm_user }}/.gvm && source /home/{{ gvm_user }}/.gvm/scripts/gvm && gvm use go1.4 && gvm install {{ go_version }}"
  ignore_errors: true

- name: Wget direnv binary
  sudo: yes
  sudo_user: "{{ gvm_user }}"
  command: zsh -lc "wget https://github.com/direnv/direnv/releases/download/v2.11.3/direnv.linux-386"
  ignore_errors: true

- name: make direnv
  shell: "sudo -iu {{ gvm_user }} cp direnv.linux-386 direnv && rm -rf direnv.linux-386 && chmod +x direnv && mkdir -p /home/{{ gvm_user }}/bin && mv direnv /home/{{ gvm_user}}/bin/"
  ignore_errors: true

- name: Put zshrc direnv
  sudo: yes
  sudo_user: "{{ gvm_user }}"
  lineinfile: >
    dest="~/.zshrc"
    line={{ item }}
  with_items:
    - 'export EDITOR=vim'
    - 'eval "$(direnv hook zsh)"'

- name: Make golang warking space
  shell: "sudo -iu {{ gvm_user }} mkdir -p go/src/github.com"

- name: Put .envrc
  sudo: yes
  sudo_user: "{{ gvm_user }}"
  copy: src=.envrc dest=~/go/.envrc

- name: chmod gvm dir
  command: "chown -R ec2-user:ec2-user /home/{{ gvm_user }}/.gvm/"
